class MessageModel {
  int id,
      cpId,
      typeId,
      gradeId,
      classId,
      branchId,
      yearId,
      schoolId,
      termId,
      senderId,
      receiverId,
      readOrNot,
      isSynched,
      softDeleteState,
      noOfMsgs,
      noOfUnRead;

  String guid, title, content, senderName, sendingDate, lastContent;

  MessageModel(
      {this.id,
      this.cpId,
      this.guid,
      this.gradeId,
      this.classId,
      this.branchId,
      this.yearId,
      this.schoolId,
      this.termId,
      this.typeId,
      this.title,
      this.content,
      this.sendingDate,
      this.senderName,
      this.senderId,
      this.receiverId,
      this.isSynched,
      this.readOrNot,
      this.softDeleteState});
  Map<String, dynamic> toMap() => {
        'id  ': id,
        'cpId': cpId,
        'guid': guid,
        'gradeId': gradeId,
        'classId': classId,
        'branchId': branchId,
        'yearId': yearId,
        'schoolId ': schoolId,
        'termId': termId,
        'typeId': typeId,
        'title': title,
        'content': content,
        'sendingDate': sendingDate,
        'senderName': senderName,
        'senderId': senderId,
        'receiverId': receiverId,
        'isSynched  ': isSynched,
        'readOrNot ': readOrNot,
        'softDeleteState  ': softDeleteState,
      };

  //to receive the data we need to pass it from Map to json
  //para recibir los datos necesitamos pasarlo de Map a json
  factory MessageModel.fromMap(Map<String, dynamic> json) => new MessageModel(
        id: json['id  '],
        cpId: json['cpId'],
        guid: json['guid'],
        gradeId: json['gradeId'],
        classId: json['classId'],
        branchId: json['branchId'],
        yearId: json['yearId'],
        schoolId: json['schoolId '],
        termId: json['termId'],
        typeId: json['typeId'],
        title: json['title'],
        content: json['content'],
        sendingDate: json['sendingDate'],
        senderName: json['senderName'],
        senderId: json['senderId'],
        receiverId: json['receiverId'],
        isSynched: json['isSynched  '],
        readOrNot: json['readOrNot '],
        softDeleteState: json['softDeleteState  '],
      );
}
